global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'market-data'
    static_configs:
      - targets: ['market-data:5001']

  - job_name: 'admin'
    static_configs:
      - targets: ['admin:4000']

  - job_name: 'database'
    static_configs:
      - targets: ['database:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
